version: '3'

services:
  amazing-co-ravneet-container:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=test@1234
      - MYSQL_DATABASE=mysqldb
      - MYSQL_USER=ravneetuser
      - MYSQL_PASSWORD=test@1234
    volumes:
      - /data/mysql
  amazing-co-app:
    image: amazing-co-image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - amazing-co-ravneet-container
    ports:
      - 8087:8080
    volumes:
      - /data/amazing-co-app
